# 6CS012 – Artificial Intelligence and Machine Learning
## Worksheet - 0: A Tutorial and Assessment on Python and NumPy for Deep Learning
Name: Samir Gurung
Uid:2438443

---
# Section 3 – Getting Started (Run These First)
### Python Version Check

In [1]:
import sys

if sys.version_info.major == 3 and sys.version_info.minor >= 6:
    print("Hello, World!")
    print(f"Python version: {sys.version}")
else:
    print("Please use Python 3.6 or higher.")

Hello, World!
Python version: 3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]


In [2]:
import numpy as np
import time
print("NumPy version:", np.__version__)

NumPy version: 2.0.2


---
# Section 4.1 – Exercise on Functions

## Task 1 – Unit Converter


In [3]:
# ── Conversion Functions ───────────────────────────────────────────────────

def convert_length(value, direction):
    """
    Convert between meters and feet.

    Parameters:
        value     (float): The numeric value to convert.
        direction (str)  : 'mtf' for meters-to-feet, 'ftm' for feet-to-meters.

    Returns:
        float: The converted value.

    Raises:
        ValueError: If direction is not 'mtf' or 'ftm'.
    """
    if direction == 'mtf':
        result = value * 3.28084
        print(f"{value} meters = {result:.4f} feet")
    elif direction == 'ftm':
        result = value / 3.28084
        print(f"{value} feet = {result:.4f} meters")
    else:
        raise ValueError("Invalid direction. Use 'mtf' or 'ftm'.")
    return result


def convert_weight(value, direction):
    """
    Convert between kilograms and pounds.

    Parameters:
        value     (float): The numeric value to convert.
        direction (str)  : 'ktl' for kg-to-lbs, 'ltk' for lbs-to-kg.

    Returns:
        float: The converted value.

    Raises:
        ValueError: If direction is not 'ktl' or 'ltk'.
    """
    if direction == 'ktl':
        result = value * 2.20462
        print(f"{value} kg = {result:.4f} lbs")
    elif direction == 'ltk':
        result = value / 2.20462
        print(f"{value} lbs = {result:.4f} kg")
    else:
        raise ValueError("Invalid direction. Use 'ktl' or 'ltk'.")
    return result


def convert_volume(value, direction):
    """
    Convert between liters and gallons.

    Parameters:
        value     (float): The numeric value to convert.
        direction (str)  : 'ltg' for liters-to-gallons, 'gtl' for gallons-to-liters.

    Returns:
        float: The converted value.

    Raises:
        ValueError: If direction is not 'ltg' or 'gtl'.
    """
    if direction == 'ltg':
        result = value * 0.264172
        print(f"{value} liters = {result:.4f} gallons")
    elif direction == 'gtl':
        result = value / 0.264172
        print(f"{value} gallons = {result:.4f} liters")
    else:
        raise ValueError("Invalid direction. Use 'ltg' or 'gtl'.")
    return result


def unit_converter():
    """
    Main unit converter program.

    Prompts the user to choose a conversion type (length, weight, volume),
    a direction, and a numeric value. Handles invalid inputs with try-except.

    Returns:
        float or None: The converted value, or None if an error occurs.
    """
    print("========== Unit Converter ==========")
    print("Choose conversion type:")
    print("  1. Length  (meters ↔ feet)")
    print("  2. Weight  (kg ↔ lbs)")
    print("  3. Volume  (liters ↔ gallons)")

    try:
        choice = input("Enter 1, 2 or 3: ").strip()

        if choice == '1':
            print("Direction: 'mtf' = meters→feet  |  'ftm' = feet→meters")
            direction = input("Enter direction (mtf / ftm): ").strip().lower()
            value = float(input("Enter value: "))
            return convert_length(value, direction)

        elif choice == '2':
            print("Direction: 'ktl' = kg→lbs  |  'ltk' = lbs→kg")
            direction = input("Enter direction (ktl / ltk): ").strip().lower()
            value = float(input("Enter value: "))
            return convert_weight(value, direction)

        elif choice == '3':
            print("Direction: 'ltg' = liters→gallons  |  'gtl' = gallons→liters")
            direction = input("Enter direction (ltg / gtl): ").strip().lower()
            value = float(input("Enter value: "))
            return convert_volume(value, direction)

        else:
            print("Invalid choice. Please enter 1, 2, or 3.")
            return None

    except ValueError as e:
        print(f"Error: {e}. Please enter a valid numeric value.")
        return None


# ── Demo without interactive input ────────────────────────────────────────
print("=== Demo Conversions ===")
convert_length(5,   'mtf')   # 5 meters -> feet
convert_weight(70,  'ktl')   # 70 kg -> lbs
convert_volume(3.5, 'ltg')   # 3.5 liters -> gallons

# Uncomment the line below to run interactively in Colab
# unit_converter()

=== Demo Conversions ===
5 meters = 16.4042 feet
70 kg = 154.3234 lbs
3.5 liters = 0.9246 gallons


0.924602

## Task 2 – Mathematical Operations on a List of Numbers

In [4]:
# ── Individual Operation Functions ────────────────────────────────────────

def compute_sum(numbers):
    """
    Compute the sum of a list of numbers.

    Parameters:
        numbers (list): A non-empty list of numeric values.

    Returns:
        float: The sum of all elements.

    Raises:
        ValueError: If the list is empty.
    """
    if not numbers:
        raise ValueError("List is empty.")
    total = 0
    for n in numbers:
        total += n
    return total


def compute_average(numbers):
    """
    Compute the average (mean) of a list of numbers.

    Parameters:
        numbers (list): A non-empty list of numeric values.

    Returns:
        float: The average value.

    Raises:
        ValueError: If the list is empty.
    """
    if not numbers:
        raise ValueError("List is empty.")
    return compute_sum(numbers) / len(numbers)


def compute_maximum(numbers):
    """
    Find the maximum value in a list of numbers.

    Parameters:
        numbers (list): A non-empty list of numeric values.

    Returns:
        float: The maximum element.

    Raises:
        ValueError: If the list is empty.
    """
    if not numbers:
        raise ValueError("List is empty.")
    max_val = numbers[0]
    for n in numbers:
        if n > max_val:
            max_val = n
    return max_val


def compute_minimum(numbers):
    """
    Find the minimum value in a list of numbers.

    Parameters:
        numbers (list): A non-empty list of numeric values.

    Returns:
        float: The minimum element.

    Raises:
        ValueError: If the list is empty.
    """
    if not numbers:
        raise ValueError("List is empty.")
    min_val = numbers[0]
    for n in numbers:
        if n < min_val:
            min_val = n
    return min_val


def math_operations_menu():
    """
    Interactive menu to perform math operations on a user-supplied list of numbers.

    Returns:
        float or None: Result of the selected operation, or None on error.
    """
    print("========== Math Operations ==========")
    print("Choose operation:")
    print("  1. Sum")
    print("  2. Average")
    print("  3. Maximum")
    print("  4. Minimum")

    try:
        choice   = input("Enter 1, 2, 3 or 4: ").strip()
        raw      = input("Enter numbers separated by spaces: ")
        numbers  = [float(x) for x in raw.split()]

        ops = {'1': compute_sum, '2': compute_average,
               '3': compute_maximum, '4': compute_minimum}

        if choice not in ops:
            print("Invalid choice.")
            return None

        result = ops[choice](numbers)
        print(f"Result: {result}")
        return result

    except ValueError as e:
        print(f"Error: {e}")
        return None


# ── Demo ──────────────────────────────────────────────────────────────────
demo_numbers = [4, 7, 2, 9, 1, 5]
print("Demo list:", demo_numbers)
print("Sum     :", compute_sum(demo_numbers))
print("Average :", compute_average(demo_numbers))
print("Maximum :", compute_maximum(demo_numbers))
print("Minimum :", compute_minimum(demo_numbers))

# Error handling demo
try:
    compute_sum([])
except ValueError as e:
    print(f"\nExpected Error caught: {e}")

# Uncomment to run interactively
# math_operations_menu()

Demo list: [4, 7, 2, 9, 1, 5]
Sum     : 28
Average : 4.666666666666667
Maximum : 9
Minimum : 1

Expected Error caught: List is empty.


---
# Section 4.2 – Exercise on List Manipulation
### Task 1 – Extract Every Other Element

In [5]:
def extract_every_other(lst):
    """
    Extract every other element from a list, starting from the first element.

    Parameters:
        lst (list): Input list.

    Returns:
        list: New list containing every other element (index 0, 2, 4, ...).

    Example:
        >>> extract_every_other([1, 2, 3, 4, 5, 6])
        [1, 3, 5]
    """
    return lst[::2]


print(extract_every_other([1, 2, 3, 4, 5, 6]))   # [1, 3, 5]

[1, 3, 5]


### Task 2 – Slice a Sublist

In [6]:
def get_sublist(lst, start, end):
    """
    Return a sublist from a given list between start and end indices (inclusive).

    Parameters:
        lst   (list): Input list.
        start (int) : Starting index (inclusive).
        end   (int) : Ending index (inclusive).

    Returns:
        list: Sublist from start to end inclusive.

    Example:
        >>> get_sublist([1, 2, 3, 4, 5, 6], 2, 4)
        [3, 4, 5]
    """
    return lst[start:end + 1]


print(get_sublist([1, 2, 3, 4, 5, 6], 2, 4))    # [3, 4, 5]

[3, 4, 5]


### Task 3 – Reverse a List Using Slicing

In [7]:
def reverse_list(lst):
    """
    Reverse a list using slicing.

    Parameters:
        lst (list): Input list.

    Returns:
        list: Reversed list.

    Example:
        >>> reverse_list([1, 2, 3, 4, 5])
        [5, 4, 3, 2, 1]
    """
    return lst[::-1]


print(reverse_list([1, 2, 3, 4, 5]))             # [5, 4, 3, 2, 1]

[5, 4, 3, 2, 1]


### Task 4 – Remove the First and Last Elements

In [8]:
def remove_first_last(lst):
    """
    Remove the first and last elements of a list using slicing.

    Parameters:
        lst (list): Input list (must have at least 2 elements).

    Returns:
        list: Sublist without the first and last elements.

    Example:
        >>> remove_first_last([1, 2, 3, 4, 5])
        [2, 3, 4]
    """
    return lst[1:-1]


print(remove_first_last([1, 2, 3, 4, 5]))        # [2, 3, 4]

[2, 3, 4]


### Task 5 – Get the First n Elements

In [9]:
def get_first_n(lst, n):
    """
    Extract the first n elements from a list.

    Parameters:
        lst (list): Input list.
        n   (int) : Number of elements to extract from the front.

    Returns:
        list: First n elements.

    Example:
        >>> get_first_n([1, 2, 3, 4, 5], 3)
        [1, 2, 3]
    """
    return lst[:n]


print(get_first_n([1, 2, 3, 4, 5], 3))           # [1, 2, 3]

[1, 2, 3]


### Task 6 – Extract Elements from the End

In [10]:
def get_last_n(lst, n):
    """
    Extract the last n elements from a list.

    Parameters:
        lst (list): Input list.
        n   (int) : Number of elements to extract from the end.

    Returns:
        list: Last n elements.

    Example:
        >>> get_last_n([1, 2, 3, 4, 5], 2)
        [4, 5]
    """
    return lst[-n:]


print(get_last_n([1, 2, 3, 4, 5], 2))            # [4, 5]

[4, 5]


### Task 7 – Extract Elements in Reverse Order (skip one, from second-to-last)

In [11]:
def reverse_skip(lst):
    """
    Extract every second element starting from the second-to-last, moving backward.

    Parameters:
        lst (list): Input list.

    Returns:
        list: Elements at indices -2, -4, -6, ... (every other, reversed).

    Example:
        >>> reverse_skip([1, 2, 3, 4, 5, 6])
        [5, 3, 1]
    """
    return lst[-2::-2]


print(reverse_skip([1, 2, 3, 4, 5, 6]))          # [5, 3, 1]

[5, 3, 1]


---
# Section 4.3 – Exercise on Nested Lists
### Task 1 – Flatten a Nested List

In [12]:
def flatten(lst):
    """
    Flatten a one-level nested list into a single list.

    Parameters:
        lst (list): A nested list (one level deep).

    Returns:
        list: Flattened single-dimensional list.

    Example:
        >>> flatten([[1, 2], [3, 4], [5]])
        [1, 2, 3, 4, 5]
    """
    result = []
    for sublist in lst:
        for item in sublist:
            result.append(item)
    return result


print(flatten([[1, 2], [3, 4], [5]]))             # [1, 2, 3, 4, 5]

[1, 2, 3, 4, 5]


### Task 2 – Accessing Nested List Elements

In [13]:
def access_nested_element(lst, indices):
    """
    Extract a specific element from a nested list using a sequence of indices.

    Parameters:
        lst     (list): A nested list.
        indices (list): A list of integer indices to traverse the nesting.

    Returns:
        The element at the specified nested position.

    Example:
        >>> access_nested_element([[1,2,3],[4,5,6],[7,8,9]], [1, 2])
        6
    """
    element = lst
    for idx in indices:
        element = element[idx]
    return element


lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(access_nested_element(lst, [1, 2]))         # 6

6


### Task 3 – Sum of All Elements in a Nested List

In [14]:
def sum_nested(lst):
    """
    Calculate the sum of all numbers in a nested list (any depth).

    Parameters:
        lst (list): A nested list of numbers (arbitrary depth).

    Returns:
        float: Sum of all numeric elements.

    Example:
        >>> sum_nested([[1, 2], [3, [4, 5]], 6])
        21
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)   # Recursive call
        else:
            total += item
    return total


print(sum_nested([[1, 2], [3, [4, 5]], 6]))       # 21

21


### Task 4 – Remove Specific Element from a Nested List

In [15]:
def remove_element(lst, elem):
    """
    Remove all occurrences of a specific element from a nested list.

    Parameters:
        lst  (list): A nested list.
        elem       : The element to remove.

    Returns:
        list: Modified nested list with all occurrences of elem removed.

    Example:
        >>> remove_element([[1, 2], [3, 2], [4, 5]], 2)
        [[1], [3], [4, 5]]
    """
    return [[x for x in sublist if x != elem] for sublist in lst]


print(remove_element([[1, 2], [3, 2], [4, 5]], 2))  # [[1], [3], [4, 5]]

[[1], [3], [4, 5]]


### Task 5 – Find Maximum Element in a Nested List

In [16]:
def find_max(lst):
    """
    Find the maximum element in a nested list (any depth).

    Parameters:
        lst (list): A nested list of numbers.

    Returns:
        The maximum numeric element found.

    Example:
        >>> find_max([[1, 2], [3, [4, 5]], 6])
        6
    """
    max_val = None
    for item in lst:
        if isinstance(item, list):
            candidate = find_max(item)
        else:
            candidate = item
        if max_val is None or candidate > max_val:
            max_val = candidate
    return max_val


print(find_max([[1, 2], [3, [4, 5]], 6]))          # 6

6


### Task 6 – Count Occurrences of an Element in a Nested List

In [17]:
def count_occurrences(lst, elem):
    """
    Count how many times a specific element appears in a nested list.

    Parameters:
        lst  (list): A nested list.
        elem       : The element to count.

    Returns:
        int: Number of occurrences of elem in the nested list.

    Example:
        >>> count_occurrences([[1, 2], [2, 3], [2, 4]], 2)
        3
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count


print(count_occurrences([[1, 2], [2, 3], [2, 4]], 2))  # 3

3


### Task 7 – Deep Flatten (Any Depth)

In [18]:
def deep_flatten(lst):
    """
    Flatten a deeply nested list into a single flat list (any depth).

    Parameters:
        lst (list): A deeply nested list.

    Returns:
        list: A single flat list containing all elements.

    Example:
        >>> deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
        [1, 2, 3, 4, 5, 6, 7, 8]
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result


print(deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))  # [1,2,3,4,5,6,7,8]

[1, 2, 3, 4, 5, 6, 7, 8]


### Task 8 – Nested List Average

In [ ]:
def average_nested(lst):
    """
    Calculate the average of all elements in a nested list.

    Parameters:
        lst (list): A nested list of numbers.

    Returns:
        float: The average of all numeric elements.

    Example:
        >>> average_nested([[1, 2], [3, 4], [5, 6]])
        3.5
    """
    flat = deep_flatten(lst)
    return sum(flat) / len(flat)


print(average_nested([[1, 2], [3, 4], [5, 6]]))    # 3.5

---
# Section 10.1 – Basic Vector and Matrix Operations with NumPy

## Problem 1 – Array Creation

In [19]:
import numpy as np

# 1. Initialize an empty array of size 2x2
empty_2x2 = np.empty((2, 2))
print("1. Empty 2x2 array:\n", empty_2x2)

# 2. Initialize an all-ones array of size 4x2
ones_4x2 = np.ones((4, 2))
print("\n2. Ones 4x2 array:\n", ones_4x2)

# 3. Array filled with a specific fill_value using np.full
fill_val = 7
full_arr = np.full((3, 3), fill_val)
print(f"\n3. np.full (3x3) filled with {fill_val}:\n", full_arr)

# 4. np.zeros_like – zeros array with same shape and type as a given array
reference = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_arr = np.zeros_like(reference)
print("\n4. np.zeros_like reference array:\n", zeros_like_arr)

# 5. np.ones_like – ones array with same shape and type as a given array
ones_like_arr = np.ones_like(reference)
print("\n5. np.ones_like reference array:\n", ones_like_arr)

# 6. Convert an existing Python list to a NumPy array
new_list  = [1, 2, 3, 4]
np_from_list = np.array(new_list)
print("\n6. NumPy array from list:", np_from_list, "| dtype:", np_from_list.dtype)

1. Empty 2x2 array:
 [[1.96714056e-315 0.00000000e+000]
 [6.64864109e-310 6.64864109e-310]]

2. Ones 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. np.full (3x3) filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. np.zeros_like reference array:
 [[0 0 0]
 [0 0 0]]

5. np.ones_like reference array:
 [[1 1 1]
 [1 1 1]]

6. NumPy array from list: [1 2 3 4] | dtype: int64


## Problem 2 – Array Manipulation: Numerical Ranges and Indexing

In [20]:
# 1. Array with values ranging from 10 to 49
arr_10_49 = np.arange(10, 50)
print("1. arange(10, 50):\n", arr_10_49)

# 2. 3x3 matrix with values 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 matrix (0 to 8):\n", matrix_3x3)

# 3. 3x3 identity matrix
identity = np.eye(3)
print("\n3. 3x3 Identity matrix:\n", identity)

# 4. Random array of size 30 and its mean
rand_30 = np.random.random(30)
print("\n4. Random array (size 30):", rand_30)
print("   Mean:", rand_30.mean())

# 5. 10x10 random array – min and max
rand_10x10 = np.random.random((10, 10))
print("\n5. 10x10 random array min:", rand_10x10.min(), " max:", rand_10x10.max())

# 6. Zero array of size 10 – replace 5th element with 1
zero_arr = np.zeros(10)
zero_arr[4] = 1      # index 4 = 5th element
print("\n6. Zero array with 5th element = 1:\n", zero_arr)

# 7. Reverse an array
arr_rev = np.array([1, 2, 0, 0, 4, 0])
print("\n7. Reversed array:", arr_rev[::-1])

# 8. 2D array with 1 on border and 0 inside
border_arr = np.ones((6, 6))
border_arr[1:-1, 1:-1] = 0
print("\n8. Border-ones array:\n", border_arr)

# 9. 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n9. 8x8 Checkerboard pattern:\n", checkerboard)

1. arange(10, 50):
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix (0 to 8):
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array (size 30): [0.34892139 0.21793245 0.18277373 0.27056615 0.56236041 0.60287255
 0.74477737 0.02243703 0.56804628 0.43969191 0.26778294 0.77896418
 0.26834501 0.59516887 0.46758222 0.85513311 0.25845604 0.73700403
 0.52884057 0.01629792 0.51564758 0.43179331 0.17668238 0.94484416
 0.62937365 0.72298959 0.88234041 0.47516713 0.62289255 0.79939698]
   Mean: 0.497836063319046

5. 10x10 random array min: 0.011308769115665251  max: 0.995345291831881

6. Zero array with 5th element = 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reversed array: [0 4 0 0 2 1]

8. Border-ones array:
 [[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]

9. 8x8 Checkerboard 

## Problem 3 – Array Operations

In [21]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add
print("1. x + y:\n", x + y)

# 2. Subtract
print("\n2. x - y:\n", x - y)

# 3. Multiply by scalar
scalar = 3
print(f"\n3. x * {scalar}:\n", x * scalar)

# 4. Square of each element
print("\n4. x squared (element-wise):\n", np.square(x))

# 5. Dot products
print("\n5a. Dot product v · w:", np.dot(v, w))
print("5b. Dot product x · v:\n",  np.dot(x, v))
print("5c. Dot product x · y:\n",  np.dot(x, y))

# 6. Concatenate x and y along rows (axis=0) and v and w along columns
concat_xy_rows = np.concatenate((x, y), axis=0)
print("\n6a. Concatenate x,y along rows (axis=0):\n", concat_xy_rows)
concat_vw_col  = np.vstack((v, w))
print("6b. Stack v,w (column-wise via vstack):\n", concat_vw_col)

# 7. Concatenate x and v – expected error
print("\n7. Attempting to concatenate x and v:")
try:
    result = np.concatenate((x, v))
except ValueError as e:
    print(f"  Error caught: {e}")
    print("  Explanation: x has shape (2,2) and v has shape (2,).")
    print("  They have different numbers of dimensions, so NumPy cannot")
    print("  concatenate them directly. v must be reshaped to (1,2) or (2,1) first.")

1. x + y:
 [[ 6  8]
 [10 13]]

2. x - y:
 [[-4 -4]
 [-4 -3]]

3. x * 3:
 [[ 3  6]
 [ 9 15]]

4. x squared (element-wise):
 [[ 1  4]
 [ 9 25]]

5a. Dot product v · w: 219
5b. Dot product x · v:
 [29 77]
5c. Dot product x · y:
 [[19 22]
 [50 58]]

6a. Concatenate x,y along rows (axis=0):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
6b. Stack v,w (column-wise via vstack):
 [[ 9 10]
 [11 12]]

7. Attempting to concatenate x and v:
  Error caught: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
  Explanation: x has shape (2,2) and v has shape (2,).
  They have different numbers of dimensions, so NumPy cannot
  concatenate them directly. v must be reshaped to (1,2) or (2,1) first.


## Problem 4 – Matrix Operations

In [22]:
A = np.array([[3, 4], [7, 8]], dtype=float)
B = np.array([[5, 3], [2, 1]], dtype=float)

# ── 1. Prove A · A⁻¹ = I ─────────────────────────────────────────────────
A_inv     = np.linalg.inv(A)
A_A_inv   = np.dot(A, A_inv)
print("1. A · A⁻¹ (should equal Identity):\n", np.round(A_A_inv, 6))
print("   Is it Identity?", np.allclose(A_A_inv, np.eye(2)))

# ── 2. Prove AB ≠ BA ──────────────────────────────────────────────────────
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. AB:\n", AB)
print("   BA:\n", BA)
print("   AB == BA?", np.allclose(AB, BA))

# ── 3. Prove (AB)ᵀ = BᵀAᵀ ────────────────────────────────────────────────
LHS = (np.dot(A, B)).T
RHS = np.dot(B.T, A.T)
print("\n3. (AB)ᵀ:\n", LHS)
print("   BᵀAᵀ:\n", RHS)
print("   (AB)ᵀ == BᵀAᵀ?", np.allclose(LHS, RHS))

1. A · A⁻¹ (should equal Identity):
 [[1. 0.]
 [0. 1.]]
   Is it Identity? True

2. AB:
 [[23. 13.]
 [51. 29.]]
   BA:
 [[36. 44.]
 [13. 16.]]
   AB == BA? False

3. (AB)ᵀ:
 [[23. 51.]
 [13. 29.]]
   BᵀAᵀ:
 [[23. 51.]
 [13. 29.]]
   (AB)ᵀ == BᵀAᵀ? True


In [ ]:
# ── Solve system of linear equations: AX = B ─────────────────────────────
#
#   2x - 3y + z  = -1
#   x  - y  + 2z = -3
#   3x + y  - z  =  9

A_sys = np.array([[ 2, -3,  1],
                  [ 1, -1,  2],
                  [ 3,  1, -1]], dtype=float)

B_sys = np.array([-1, -3, 9], dtype=float)

# Method 1: Inverse method  X = A⁻¹ · B
A_sys_inv = np.linalg.inv(A_sys)
X_inv     = np.dot(A_sys_inv, B_sys)
print("\nSolving 2x-3y+z=-1, x-y+2z=-3, 3x+y-z=9")
print("Method 1 (Inverse): x={:.2f}, y={:.2f}, z={:.2f}".format(*X_inv))

# Method 2: np.linalg.solve (more numerically stable)
X_solve = np.linalg.solve(A_sys, B_sys)
print("Method 2 (linalg.solve): x={:.2f}, y={:.2f}, z={:.2f}".format(*X_solve))

# Verify: A · X ≈ B
print("Verification A·X:", np.round(np.dot(A_sys, X_solve), 6), "== B:", B_sys)

---
# Section 10.2 – Experiment: How Fast is NumPy?
### 1. Element-wise Addition

In [23]:
import time
import numpy as np

SIZE = 1_000_000

# ── Python List: Element-wise Addition ────────────────────────────────────
list_a = list(range(SIZE))
list_b = list(range(SIZE))

start = time.time()
result_list = [list_a[i] + list_b[i] for i in range(SIZE)]
list_add_time = time.time() - start
print(f"Python List Addition    : {list_add_time:.5f} seconds")

# ── NumPy: Element-wise Addition ──────────────────────────────────────────
np_a = np.arange(SIZE)
np_b = np.arange(SIZE)

start = time.time()
result_np = np_a + np_b
np_add_time = time.time() - start
print(f"NumPy  Array Addition   : {np_add_time:.5f} seconds")
print(f"Speedup                 : {list_add_time / np_add_time:.1f}x faster with NumPy")

Python List Addition    : 0.12329 seconds
NumPy  Array Addition   : 0.00441 seconds
Speedup                 : 27.9x faster with NumPy


### 2. Element-wise Multiplication

In [24]:
# ── Python List: Element-wise Multiplication ──────────────────────────────
start = time.time()
result_list_mul = [list_a[i] * list_b[i] for i in range(SIZE)]
list_mul_time = time.time() - start
print(f"Python List Multiplication : {list_mul_time:.5f} seconds")

# ── NumPy: Element-wise Multiplication ────────────────────────────────────
start = time.time()
result_np_mul = np_a * np_b
np_mul_time = time.time() - start
print(f"NumPy  Array Multiplication: {np_mul_time:.5f} seconds")
print(f"Speedup                    : {list_mul_time / np_mul_time:.1f}x faster with NumPy")

Python List Multiplication : 0.11693 seconds
NumPy  Array Multiplication: 0.00488 seconds
Speedup                    : 23.9x faster with NumPy


### 3. Dot Product

In [25]:
# ── Python List: Dot Product ──────────────────────────────────────────────
start = time.time()
dot_list = sum(list_a[i] * list_b[i] for i in range(SIZE))
list_dot_time = time.time() - start
print(f"Python List Dot Product : {list_dot_time:.5f} seconds")

# ── NumPy: Dot Product ────────────────────────────────────────────────────
start = time.time()
dot_np = np.dot(np_a, np_b)
np_dot_time = time.time() - start
print(f"NumPy  Array Dot Product: {np_dot_time:.5f} seconds")
print(f"Speedup                 : {list_dot_time / np_dot_time:.1f}x faster with NumPy")

Python List Dot Product : 0.25331 seconds
NumPy  Array Dot Product: 0.00280 seconds
Speedup                 : 90.3x faster with NumPy


### 4. Matrix Multiplication (1000×1000)

In [26]:
MAT_SIZE = 1000

# ── Python List: Matrix Multiplication ────────────────────────────────────
import random
mat_a = [[random.random() for _ in range(MAT_SIZE)] for _ in range(MAT_SIZE)]
mat_b = [[random.random() for _ in range(MAT_SIZE)] for _ in range(MAT_SIZE)]

start = time.time()
result_mat_list = [[sum(mat_a[i][k] * mat_b[k][j]
                        for k in range(MAT_SIZE))
                    for j in range(MAT_SIZE)]
                   for i in range(MAT_SIZE)]
list_mat_time = time.time() - start
print(f"Python List Matrix Multiplication : {list_mat_time:.4f} seconds")

# ── NumPy: Matrix Multiplication ──────────────────────────────────────────
np_mat_a = np.array(mat_a)
np_mat_b = np.array(mat_b)

start = time.time()
result_mat_np = np.dot(np_mat_a, np_mat_b)
np_mat_time = time.time() - start
print(f"NumPy  Array Matrix Multiplication: {np_mat_time:.4f} seconds")
print(f"Speedup                           : {list_mat_time / np_mat_time:.1f}x faster with NumPy")

Python List Matrix Multiplication : 203.7094 seconds
NumPy  Array Matrix Multiplication: 0.1031 seconds
Speedup                           : 1975.0x faster with NumPy


### Performance Summary

In [27]:
print("\n" + "="*60)
print(f"{'Operation':<30} {'Python List':>12} {'NumPy':>10} {'Speedup':>10}")
print("="*60)
ops   = ["Addition", "Multiplication", "Dot Product", "Matrix Multiply (1000x1000)"]
py_t  = [list_add_time, list_mul_time, list_dot_time, list_mat_time]
np_t  = [np_add_time,   np_mul_time,   np_dot_time,   np_mat_time]
for op, p, n in zip(ops, py_t, np_t):
    print(f"{op:<30} {p:>11.5f}s {n:>9.5f}s {p/n:>9.1f}x")
print("="*60)
print("Conclusion: NumPy is significantly faster than Python loops")
print("because it uses optimised C/Fortran code under the hood.")


Operation                       Python List      NumPy    Speedup
Addition                           0.12329s   0.00441s      27.9x
Multiplication                     0.11693s   0.00488s      23.9x
Dot Product                        0.25331s   0.00280s      90.3x
Matrix Multiply (1000x1000)      203.70943s   0.10314s    1975.0x
Conclusion: NumPy is significantly faster than Python loops
because it uses optimised C/Fortran code under the hood.
